### ISSUE TITLE
为什么显示被远程主机取消

### ISSUE THREAD

**Issue by cocoILoveYoucoco** [MinhZou/FudanCourtReservation#5]
如题有以下疑问：
1.如果我要预定周六的场地，我是否需要在周四凌晨启动程序，而不能提前至周三？
2.本周我尝试在周二凌晨启动程序来预定周五的场地，但是运行没几分钟就显示被远程主机取消了操作，不知道是什么情况。
3.如果我想要预定场地，我是不是得在名额放出前几分钟再启动程序？

感谢！

**Comment by MinhZou** [comment]
1. 不需要，定时启动部分代码设置好即可。
   2. 可能是网络问题或者是访问频率过快，印象中凌晨之后直到大概早上7点左右之间系统是不开放预约的，但可以查看系统的信息。
   3. 预定的代码部分需要提前几分钟执行，但启动程序不需要。
   
   main.py函数中有注释掉的定时启动模块，这个可以在设置哪天那个时间点启动程序，后台会到时间点再开始执行任务。
    # sched = BlockingScheduler()
    # for h in [6]:
    #     sched.add_job(Client(user1_configs).scheduled_job, 'cron', day_of_week='0,2', hour=h, minute=57)
    # sched.start()

**Comment by cocoILoveYoucoco** [comment]
好的！非常感谢！！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Minhao ***@***.***&gt;
发送时间: 2024年9月4日 15:08
收件人: MinhZou/FudanCourtReservation ***@***.***&gt;
抄送: cocoILoveYoucoco ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MinhZou/FudanCourtReservation] 为什么显示被远程主机取消 (Issue #5)





  
不需要，定时启动部分代码设置好即可。
 
可能是网络问题或者是访问频率过快，印象中凌晨之后直到大概早上7点左右之间系统是不开放预约的，但可以查看系统的信息。
 
预定的代码部分需要提前几分钟执行，但启动程序不需要。
  
main.py函数中有注释掉的定时启动模块，这个可以在设置哪天那个时间点启动程序，后台会到时间点再开始执行任务。
 # sched = BlockingScheduler()
 # for h in [6]:
 #     sched.add_job(Client(user1_configs).scheduled_job, 'cron', day_of_week='0,2', hour=h, minute=57)
 # sched.start()
