### ISSUE TITLE
IP冻结

### ISSUE THREAD

**Issue by charon181** [MinhZou/FudanCourtReservation#9]
有人遇到过封IP吗？是不是有人掀桌子向信息办举报了？还是说信息办增加了其他检测方法
```
<div id="msg" class="errors">
    <h2>IP被冻结</h2>

    <p>IP已经被冻结，请稍后再试！</p>
</div>
```
还有这种
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by charon181** [comment]
![屏幕截图 2024-09-23 234027](https://github.com/user-attachments/assets/c78fe8a5-5b00-4fbd-8550-eb973e74e65f)
被复旦信息办整笑了。在最后一步预约下单前插入了一个弹窗。这个按钮怎么索引？html里面搜不到

**Comment by MinhZou** [comment]
应该是访问过频繁了，应该过一段时间会解封，实在不行，使用代理换ip就行

**Comment by charon181** [comment]
我运行了一次，抢了一个场就秒被封。是不是中间的time.sleep不能缩短？

**Comment by MinhZou** [comment]
能，但是不能太短，也不能一直发请求，具体频率没试过极限什么情况

**Comment by charon181** [comment]
现在超容易被冻结IP，信息办绝对加了反爬机制 :(
作者大大最近还能用脚本约到场吗

**Comment by MinhZou** [comment]
最近都没测试过，应该问题不大吧，反馈不是很多

**Comment by eat-slim** [comment]
> 最近都没测试过，应该问题不大吧，反馈不是很多

最近两天发现程序进不去预约场地界面了，即使我手动从网页端访问 elife，也会自动跳转到 https://[elife.fudan.edu.cn/j_spring_security_check](https://elife.fudan.edu.cn/j_spring_security_check) 这个空白网页，导致完全无法预约，信息办不会暂时把elife给关了吧......

**Comment by MinhZou** [comment]
我这边访问手动 https://elife.fudan.edu.cn 是正常的

**Comment by eat-slim** [comment]
> 我这边访问手动 https://elife.fudan.edu.cn 是正常的

我换了个账号发现也可以登陆了，所以其实就是之前的账号被ban了，估计信息办最近在查后台封号吧
